### ISSUE TITLE
关于STM32F10x_128.c可能错误的问题

### ISSUE THREAD

**Issue by mumu3w** [XIVN1987/DAPProg#3]
我仔细将此文件和STM32F10x_128.FLM做了比对，结合DAPlink项目相关代码，flash_algo中的0x20000c00应该是0x20000148（1+header_size+text_size），表示全局和静态数据段起始位置。第二个问题是0x20000400这个数值应该要大于0x20001000（stack pointer）。

**Comment by XIVN1987** [comment]
0x20000c00比0x20000148大就行，，不一定要完全一样


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mumu3w"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 上午10:08
收件人:&nbsp;"XIVN1987/DAPProg"<DAPProg@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[XIVN1987/DAPProg] 关于STM32F10x_128.c可能错误的问题 (#3)




我仔细将此文件和STM32F10x_128.FLM做了比对，结合DAPlink项目相关代码，flash_algo中的0x20000c00应该是0x20000148（1+header_size+text_size），表示全局和静态数据段起始位置。第二个问题是0x20000400这个数值应该要大于0x20001000（stack pointer）。
